import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center justify-center h-screen w-full bg-black p-4 font-jersey">
          <div className="flex items-center justify-center h-full w-full bg-black border border-dashed border-[#FFD700] text-[#FFD700] rounded-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
